#include <avr/eeprom.h>
#include "Arduino.h"
#include "config.h"
#include "def.h"
#include "types.h"
#include "EEPROM.h"
#include "MultiWii.h"
#include "Alarms.h"
#include "GPS.h"

#define PLEVELSCALE 50

/* autogenerated Mon Apr 20 09:51:46 2015 */
conf.powerTrigger1 = 0 / PLEVELSCALE;
conf.pid[PIDALT].D8 = 24;
conf.pid[YAW].I8 = 373.31;
conf.pid[PITCH].P8 = 35.928;
conf.yawRate = 0;
conf.pid[YAW].D8 = 6.162;
conf.pid[PIDVEL].P8 = 0;
conf.pid[PITCH].I8 = 271.18;
conf.pid[ROLL].P8 = 35.825;
conf.pid[PITCH].D8 = 4.4762;
conf.pid[PIDVEL].I8 = 0;
conf.pid[PIDMAG].P8 = 40;
conf.pid[ROLL].I8 = 270.41;
conf.pid[PIDVEL].D8 = 0;
conf.pid[ROLL].D8 = 4.4634;
conf.pid[PIDLEVEL].P8 = 90;
conf.rcRate8 = 90;
conf.thrMid8 = 50;
conf.rollPitchRate = 0;
conf.pid[PIDLEVEL].I8 = 10;
conf.pid[PIDNAVR].P8 = 25;
conf.pid[PIDLEVEL].D8 = 100;
conf.pid[PIDNAVR].I8 = 330;
conf.rcExpo8 = 75;
conf.pid[PIDPOSR].P8 = 34;
conf.pid[PIDNAVR].D8 = 8.3;
conf.pid[PIDPOSR].I8 = 140;
conf.dynThrPID = 0;
conf.pid[PIDPOS].P8 = 15;
conf.pid[PIDPOSR].D8 = 53;
conf.pid[PIDPOS].I8 = 0;
conf.pid[PIDALT].P8 = 64;
conf.pid[PIDPOS].D8 = 0;
conf.pid[PIDALT].I8 = 25;
conf.thrExpo8 = 0;
conf.pid[YAW].P8 = 49.459;



    for(uint8_t i=0;i<CHECKBOXITEMS;i++) {conf.activate[i] = 0;}
    conf.angleTrim[0] = 0; conf.angleTrim[1] = 0;

